linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - gofmt
    - gosimple
    - ineffassign
    - unused

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
