name: Update krew-index

on:
  release:
    types: [published]

jobs:
  krew-update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: rajatjindal/krew-release-bot@v0.0.46
